name: New Chart
description: New Chart Request Form
title: "[Chart]: "
labels: ["chart"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to request a new chart!
  - type: input
    id: title
    attributes:
      label: Chart Title
      description: Enter a descriptive chart title
      placeholder: ex. Disk Read Response Time by Interval
    validations:
      required: true
  - type: dropdown
    id: category
    attributes:
      label: Category Name
      description: Select the Index Category Name this chart belongs to.
      multiple: false
      options:
        - Client
        - Processes
        - Resources
        - Storage Pools
        - Workload
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: Chart Type
      description: Select the Chart Type
      multiple: false
      options:
        - Client
        - Processes
        - Resources
        - Storage Pools
        - Workload
  - type: dropdown
    id: category
    attributes:
      label: Category Name
      description: Select the Index Category Name this chart belongs to.
      multiple: false
      options:
        - Area
        - Bar (horizontal)
        - Stacked Bar (horizontal)
        - Columns (vertical)
        - Stacked Columns (vertical)
        - Line
        - Scatter
        - Pie
    validations:
      required: true
        - Workload
    validations:
      required: true
