name: New Chart
description: New Chart Request Form
title: "[Chart]: "
labels: ["chart"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to request a new chart!
  # Title
  - type: input
    id: title
    attributes:
      label: Chart Title
      description: Enter a descriptive chart title
      placeholder: ex. Disk Read Response Time by Interval
    validations:
      required: true
  # Category
  - type: dropdown
    id: category
    attributes:
      label: Category Name
      description: Select the Index Category Name this chart belongs to.
      multiple: false
      options:
        - Client
        - Processes
        - Resources
        - Storage Pools
        - Workload
    validations:
      required: true
  # Chart Type
  - type: dropdown
    id: type
    attributes:
      label: Chart Type
      description: Select the Chart Type to create
      multiple: false
      options:
        - Area
        - Bar (horizontal)
        - Stacked Bar (horizontal)
        - Columns (vertical)
        - Stacked Columns (vertical)
        - Line
        - Scatter
        - Pie
    validations:
      required: true
       

  # Chart Description
  
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Enter a detailed chart description and explanation on values.
      placeholder: "This chart shows the average latency or response for the I/O operations related to a specific set of disks (database, logs, storage pools, etc.) by interval. The purpose is to show how quickly the I/O subsystem is completing I/O requests. The chart shows the average response time by interval. The purpose of this chart is to identify how the disks are performing over time. For database and active log disks that should be an SSD, the response time should be below 5 milliseconds, ideally under 3 milliseconds. For archive logs and storage pool disks, that are normally on hard disks, the response time should be below 10 milliseconds."
      
    validations:
      required: true

# Chart Screenshot
  
  - type: textarea
    id: screenshot
    attributes:
      label: Screenshot
      description: Paste a sample screenshot of the chart here.
      placeholder: "Paste a sample screenshot of the chart here."
      
    validations:
      required: true
  
  
    # X-axis
  - type: input
    id: xaxis-label
    attributes:
      label: X-axis label
      description: X-axis label name (enter NONE if not needed)
      placeholder: X-axis label name (enter NONE if not needed)
    validations:
      required: true
# Y-axis      
   - type: input
    id: yaxis-label
    attributes:
      label: y-axis label
      description: Y-axis label name (enter NONE if not needed)
      placeholder: Y-axis label name (enter NONE if not needed). This can be the unit of measure, example: milliseconds, GB/sec, seconds, etc.
    validations:
      required: true
      
# Number of decimals.
   - type: input
    id: decimal
    attributes:
      label: decimal
      description: Enter the number of decimal places. 0 for large numbers, 3 if seconds from instrumentation.
      placeholder:Enter the number of decimal places.
    validations:
      required: true
