name: New Chart
description: New Chart Request Form
title: "[Chart]: "
labels: ["chart"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to request a new chart!
  # Title
  - type: input
    id: title
    attributes:
      label: Graph Title
      description: Enter a descriptive chart title. Use %s in the title to represent a variable that will change for when there's multiple graphs of the same type.
      placeholder: ex. %s Disk Read Response Time by Interval
    validations:
      required: true
      
  # titleVariable
  - type: input
    id: titleVariable
    attributes:
      label: Title Variable
      description: Enter a what %s represents in the Graph Title if applicable, it should be one of the values returned by the SQL query.
      placeholder: diskUse  
    validations:
      required: true
      
      
      
  # Category
  - type: dropdown
    id: category
    attributes:
      label: Category Name
      description: Select the Index Category Name this chart belongs to.
      multiple: false
      options:
        - Client
        - Processes
        - Resources
        - Storage Pools
        - Workload
    validations:
      required: true
  
  # ExcelSheet
  - type: input
    id: ExcelSheet
    attributes:
      label: Excel Sheet Name
      description: Enter the name of the Excel spreadsheet. Don't use hyphens (-), only underscores (_) if needed. 31 characters maximum
      placeholder: ex. INSTR_Time_Cat_I
    validations:
      required: true
      characterLimit: 25,31
  
  # HTML filename
  - type: input
    id: htmlFilename
    attributes:
      label: HTML Filename
      description: Enter the HTML filename, no spaces.
      placeholder: ex. instr_time_cat.html
    validations:
      required: true
  
  # Chart Type
  - type: dropdown
    id: type
    attributes:
      label: Chart Type
      description: Select the Chart Type to create
      multiple: false
      options:
        - Area
        - Bar (horizontal)
        - Stacked Bar (horizontal)
        - Columns (vertical)
        - Stacked Columns (vertical)
        - Line
        - Scatter
        - Pie
    validations:
      required: true
       

  # Chart Description
  
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Enter a detailed chart description and explanation on values.
      placeholder: "This chart shows the average latency or response for the I/O operations related to a specific set of disks (database, logs, storage pools, etc.) by interval. The purpose is to show how quickly the I/O subsystem is completing I/O requests. The chart shows the average response time by interval. The purpose of this chart is to identify how the disks are performing over time. For database and active log disks that should be an SSD, the response time should be below 5 milliseconds, ideally under 3 milliseconds. For archive logs and storage pool disks, that are normally on hard disks, the response time should be below 10 milliseconds."
      
    validations:
      required: true

  # Chart Screenshot
  
  - type: textarea
    id: screenshot
    attributes:
      label: Screenshot
      description: Paste a sample screenshot of the chart here.
      placeholder: "Paste a sample screenshot of the chart here."
      
    validations:
      required: true

  # SQL1
  - type: textarea
    id: sql
    attributes:
      label: Primary SQL
      description: Enter the SQL query used to create this graph. If 2 queries are required, one to get a list, and a second to generate 1 graph for each item in the list, enter the first query for the list here and the second below.
      render: markdown
    validations:
      required: true
      
  # SQL2
  - type: textarea
    id: sql2
    attributes:
      label: Second SQL (optional
      description: If this graph requires 2 SQL queries, enter the 2nd one here.
      render: markdown
    
  
  # Y-axis      
  - type: input
    id: yaxis-label
    attributes:
      label: Y-axis label
      description: Y-axis label name (enter NONE if not needed)
      placeholder: "Y-axis label name (enter NONE if not needed). This can be the unit of measure, example: milliseconds, GB/sec, seconds, etc."
    validations:
      required: true
      
# Number of decimals.
  - type: dropdown
    id: decimal
    attributes:
      label: decimal
      description: Enter the number of decimal places. 0 for large numbers, 3 if seconds from instrumentation.
      multiple: false
      options:
        - 0 
        - 1
        - 2
        - 3 
        - Not applicable
    validations:
      required: true
 
