name: New Chart
description: New Chart Request Form
title: "[Chart]: "
labels: ["chart"]
assignees:
 
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to request a new chart!
  - type: input
    id: chartname
    attributes:
      label: Chart Title
      description: Please enter the chart title.
      placeholder: ex. Database Disk Response Time by Interval
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: catetogory
    attributes:
      label: Category
      description: In which index category does this report belong to?
      options:
        - Client
        - Processes
        - Resources
        - Storage Pools
        - Workload
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
   - type: textarea
    id: description
    attributes:
      label: Description:
      description: Give a detailed description of the chart as well as how to interpret it.
      placeholder: Tell us what you see!
      value: "This chart shows the average latency or response for the I/O operations related to a specific set of disks (database, logs, storage pools, etc.) by interval. The purpose is to show how quickly the I/O subsystem is completing I/O requests. The chart shows the average response time by interval. The purpose of this chart is to identify how the disks are performing over time. For database and active log disks that should be an SSD, the response time should be below 5 milliseconds, ideally under 3 milliseconds. For archive logs and storage pool disks, that are normally on hard disks, the response time should be below 10 milliseconds."
    validations:
      required: true
