name: New Chart
description: New Chart Request Form
title: "[Chart]: "
labels: ["chart"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to request a new chart!
  - type: input
    id: title
    attributes:
      label: Chart Title
      description: Enter a descriptive chart title
      placeholder: ex. Disk Read Response Time by Interval
      validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: false
      options:
        - Client
        - Processes
        - Resources
        - Storage Pools
        - Workload
