name: New Chart
description: New Chart Request Form
title: "[Chart]: "
labels: ["chart"]
assignees:
 
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to request a new chart!
 
